/******/ (function(modules) { // webpackBootstrap
/******/ 	// The module cache
/******/ 	var installedModules = {};
/******/
/******/ 	// The require function
/******/ 	function __webpack_require__(moduleId) {
/******/
/******/ 		// Check if module is in cache
/******/ 		if(installedModules[moduleId]) {
/******/ 			return installedModules[moduleId].exports;
/******/ 		}
/******/ 		// Create a new module (and put it into the cache)
/******/ 		var module = installedModules[moduleId] = {
/******/ 			i: moduleId,
/******/ 			l: false,
/******/ 			exports: {}
/******/ 		};
/******/
/******/ 		// Execute the module function
/******/ 		modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
/******/
/******/ 		// Flag the module as loaded
/******/ 		module.l = true;
/******/
/******/ 		// Return the exports of the module
/******/ 		return module.exports;
/******/ 	}
/******/
/******/
/******/ 	// expose the modules object (__webpack_modules__)
/******/ 	__webpack_require__.m = modules;
/******/
/******/ 	// expose the module cache
/******/ 	__webpack_require__.c = installedModules;
/******/
/******/ 	// define getter function for harmony exports
/******/ 	__webpack_require__.d = function(exports, name, getter) {
/******/ 		if(!__webpack_require__.o(exports, name)) {
/******/ 			Object.defineProperty(exports, name, {
/******/ 				configurable: false,
/******/ 				enumerable: true,
/******/ 				get: getter
/******/ 			});
/******/ 		}
/******/ 	};
/******/
/******/ 	// define __esModule on exports
/******/ 	__webpack_require__.r = function(exports) {
/******/ 		Object.defineProperty(exports, '__esModule', { value: true });
/******/ 	};
/******/
/******/ 	// getDefaultExport function for compatibility with non-harmony modules
/******/ 	__webpack_require__.n = function(module) {
/******/ 		var getter = module && module.__esModule ?
/******/ 			function getDefault() { return module['default']; } :
/******/ 			function getModuleExports() { return module; };
/******/ 		__webpack_require__.d(getter, 'a', getter);
/******/ 		return getter;
/******/ 	};
/******/
/******/ 	// Object.prototype.hasOwnProperty.call
/******/ 	__webpack_require__.o = function(object, property) { return Object.prototype.hasOwnProperty.call(object, property); };
/******/
/******/ 	// __webpack_public_path__
/******/ 	__webpack_require__.p = "";
/******/
/******/
/******/ 	// Load entry module and return exports
/******/ 	return __webpack_require__(__webpack_require__.s = "./app/service-worker.js");
/******/ })
/************************************************************************/
/******/ ({

/***/ "./app/manifest/service-worker.js":
/*!****************************************!*\
  !*** ./app/manifest/service-worker.js ***!
  \****************************************/
/*! exports provided: timestamp, assets, shell, routes */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
eval("__webpack_require__.r(__webpack_exports__);\n/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, \"timestamp\", function() { return timestamp; });\n/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, \"assets\", function() { return assets; });\n/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, \"shell\", function() { return shell; });\n/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, \"routes\", function() { return routes; });\n// This file is generated by Sapper — do not edit it!\nconst timestamp = 1525839394752;\n\nconst assets = [\n\t\"favicon.png\",\n\t\"global.css\",\n\t\"great-success.png\",\n\t\"manifest.json\",\n\t\"svelte-logo-192.png\",\n\t\"svelte-logo-512.png\"\n];\n\nconst shell = [\n\t\"/client/3ff939b3ba2f839b0163/account_orders_id.account_orders_id.js\",\n\t\"/client/3ff939b3ba2f839b0163/_._.js\",\n\t\"/client/3ff939b3ba2f839b0163/_5xx._5xx.js\",\n\t\"/client/3ff939b3ba2f839b0163/_~_4xx~_5xx~account~account_items~account_items_edit~account_items_new~account_orders_id~account_set~afba5f34._~_4xx~_5xx~account~account_items~account_items_edit~account_items_new~account_orders_id~account_set~afba5f34.js\",\n\t\"/client/3ff939b3ba2f839b0163/account.account.js\",\n\t\"/client/3ff939b3ba2f839b0163/account_items.account_items.js\",\n\t\"/client/3ff939b3ba2f839b0163/0.0.js\",\n\t\"/client/3ff939b3ba2f839b0163/account_items_edit.account_items_edit.js\",\n\t\"/client/3ff939b3ba2f839b0163/account_items_new.account_items_new.js\",\n\t\"/client/3ff939b3ba2f839b0163/_4xx._4xx.js\",\n\t\"/client/3ff939b3ba2f839b0163/account_settings.account_settings.js\",\n\t\"/client/3ff939b3ba2f839b0163/account_settings_add_card.account_settings_add_card.js\",\n\t\"/client/3ff939b3ba2f839b0163/account_settings_edit_card.account_settings_edit_card.js\",\n\t\"/client/3ff939b3ba2f839b0163/artist_id.artist_id.js\",\n\t\"/client/3ff939b3ba2f839b0163/callback.callback.js\",\n\t\"/client/3ff939b3ba2f839b0163/item_id.item_id.js\",\n\t\"/client/3ff939b3ba2f839b0163/main.js\",\n\t\"/client/3ff939b3ba2f839b0163/publisher_id.publisher_id.js\",\n\t\"/client/3ff939b3ba2f839b0163/user_id.user_id.js\"\n];\n\nconst routes = [\n\t{ pattern: /^\\/?$/ },\n\t{ pattern: /^\\/publisher\\/id\\/?$/ },\n\t{ pattern: /^\\/callback\\/?$/ },\n\t{ pattern: /^\\/account\\/?$/ },\n\t{ pattern: /^\\/account\\/settings\\/?$/ },\n\t{ pattern: /^\\/account\\/settings\\/edit-card\\/?$/ },\n\t{ pattern: /^\\/account\\/settings\\/add-card\\/?$/ },\n\t{ pattern: /^\\/account\\/orders\\/id\\/?$/ },\n\t{ pattern: /^\\/account\\/items\\/?$/ },\n\t{ pattern: /^\\/account\\/items\\/edit\\/?$/ },\n\t{ pattern: /^\\/account\\/items\\/new\\/?$/ },\n\t{ pattern: /^\\/artist\\/id\\/?$/ },\n\t{ pattern: /^\\/user\\/id\\/?$/ },\n\t{ pattern: /^\\/item\\/id\\/?$/ }\n];\n\n//# sourceURL=webpack:///./app/manifest/service-worker.js?");

/***/ }),

/***/ "./app/service-worker.js":
/*!*******************************!*\
  !*** ./app/service-worker.js ***!
  \*******************************/
/*! no exports provided */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
eval("__webpack_require__.r(__webpack_exports__);\n/* harmony import */ var _manifest_service_worker_js__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./manifest/service-worker.js */ \"./app/manifest/service-worker.js\");\n\n\nconst ASSETS = `cache${_manifest_service_worker_js__WEBPACK_IMPORTED_MODULE_0__[\"timestamp\"]}`;\n\n// `shell` is an array of all the files generated by webpack,\n// `assets` is an array of everything in the `assets` directory\nconst to_cache = _manifest_service_worker_js__WEBPACK_IMPORTED_MODULE_0__[\"shell\"].concat(_manifest_service_worker_js__WEBPACK_IMPORTED_MODULE_0__[\"assets\"]);\nconst cached = new Set(to_cache);\n\nself.addEventListener('install', event => {\n\tevent.waitUntil(\n\t\tcaches\n\t\t\t.open(ASSETS)\n\t\t\t.then(cache => cache.addAll(to_cache))\n\t\t\t.then(() => {\n\t\t\t\tself.skipWaiting();\n\t\t\t})\n\t);\n});\n\nself.addEventListener('activate', event => {\n\tevent.waitUntil(\n\t\tcaches.keys().then(async keys => {\n\t\t\t// delete old caches\n\t\t\tfor (const key of keys) {\n\t\t\t\tif (key !== ASSETS) await caches.delete(key);\n\t\t\t}\n\n\t\t\tself.clients.claim();\n\t\t})\n\t);\n});\n\nself.addEventListener('fetch', event => {\n\tconst url = new URL(event.request.url);\n\n\t// don't try to handle e.g. data: URIs\n\tif (!url.protocol.startsWith('http')) return;\n\n\t// ignore dev server requests\n\tif (url.hostname === self.location.hostname && url.port !== self.location.port) return;\n\n\t// always serve assets and webpack-generated files from cache\n\tif (url.host === self.location.host && cached.has(url.pathname)) {\n\t\tevent.respondWith(caches.match(event.request));\n\t\treturn;\n\t}\n\n\t// for pages, you might want to serve a shell `index.html` file,\n\t// which Sapper has generated for you. It's not right for every\n\t// app, but if it's right for yours then uncomment this section\n\t/*\n\tif (url.origin === self.origin && routes.find(route => route.pattern.test(url.pathname))) {\n\t\tevent.respondWith(caches.match('/index.html'));\n\t\treturn;\n\t}\n\t*/\n\n\t// for everything else, try the network first, falling back to\n\t// cache if the user is offline. (If the pages never change, you\n\t// might prefer a cache-first approach to a network-first one.)\n\tevent.respondWith(\n\t\tcaches\n\t\t\t.open(`offline${_manifest_service_worker_js__WEBPACK_IMPORTED_MODULE_0__[\"timestamp\"]}`)\n\t\t\t.then(async cache => {\n\t\t\t\ttry {\n\t\t\t\t\tconst response = await fetch(event.request);\n\t\t\t\t\tcache.put(event.request, response.clone());\n\t\t\t\t\treturn response;\n\t\t\t\t} catch(err) {\n\t\t\t\t\tconst response = await cache.match(event.request);\n\t\t\t\t\tif (response) return response;\n\n\t\t\t\t\tthrow err;\n\t\t\t\t}\n\t\t\t})\n\t);\n});\n\n\n//# sourceURL=webpack:///./app/service-worker.js?");

/***/ })

/******/ });