module.exports =
/******/ (function(modules) { // webpackBootstrap
/******/ 	// The module cache
/******/ 	var installedModules = {};
/******/
/******/ 	// object to store loaded and loading wasm modules
/******/ 	var installedWasmModules = {};
/******/
/******/ 	// The require function
/******/ 	function __webpack_require__(moduleId) {
/******/
/******/ 		// Check if module is in cache
/******/ 		if(installedModules[moduleId]) {
/******/ 			return installedModules[moduleId].exports;
/******/ 		}
/******/ 		// Create a new module (and put it into the cache)
/******/ 		var module = installedModules[moduleId] = {
/******/ 			i: moduleId,
/******/ 			l: false,
/******/ 			exports: {}
/******/ 		};
/******/
/******/ 		// Execute the module function
/******/ 		modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
/******/
/******/ 		// Flag the module as loaded
/******/ 		module.l = true;
/******/
/******/ 		// Return the exports of the module
/******/ 		return module.exports;
/******/ 	}
/******/
/******/
/******/ 	// expose the modules object (__webpack_modules__)
/******/ 	__webpack_require__.m = modules;
/******/
/******/ 	// expose the module cache
/******/ 	__webpack_require__.c = installedModules;
/******/
/******/ 	// define getter function for harmony exports
/******/ 	__webpack_require__.d = function(exports, name, getter) {
/******/ 		if(!__webpack_require__.o(exports, name)) {
/******/ 			Object.defineProperty(exports, name, {
/******/ 				configurable: false,
/******/ 				enumerable: true,
/******/ 				get: getter
/******/ 			});
/******/ 		}
/******/ 	};
/******/
/******/ 	// define __esModule on exports
/******/ 	__webpack_require__.r = function(exports) {
/******/ 		Object.defineProperty(exports, '__esModule', { value: true });
/******/ 	};
/******/
/******/ 	// getDefaultExport function for compatibility with non-harmony modules
/******/ 	__webpack_require__.n = function(module) {
/******/ 		var getter = module && module.__esModule ?
/******/ 			function getDefault() { return module['default']; } :
/******/ 			function getModuleExports() { return module; };
/******/ 		__webpack_require__.d(getter, 'a', getter);
/******/ 		return getter;
/******/ 	};
/******/
/******/ 	// Object.prototype.hasOwnProperty.call
/******/ 	__webpack_require__.o = function(object, property) { return Object.prototype.hasOwnProperty.call(object, property); };
/******/
/******/ 	// __webpack_public_path__
/******/ 	__webpack_require__.p = "";
/******/
/******/ 	// object with all compiled WebAssembly.Modules
/******/ 	__webpack_require__.w = {};
/******/
/******/
/******/ 	// Load entry module and return exports
/******/ 	return __webpack_require__(__webpack_require__.s = "./app/server.js");
/******/ })
/************************************************************************/
/******/ ({

/***/ "./app/manifest/server.js":
/*!********************************!*\
  !*** ./app/manifest/server.js ***!
  \********************************/
/*! exports provided: routes */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
eval("__webpack_require__.r(__webpack_exports__);\n/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, \"routes\", function() { return routes; });\n/* harmony import */ var _routes_index_html__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ../../routes/index.html */ \"./routes/index.html\");\n/* harmony import */ var _routes_callback_html__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ../../routes/callback.html */ \"./routes/callback.html\");\n/* harmony import */ var _routes_4xx_html__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! ../../routes/4xx.html */ \"./routes/4xx.html\");\n/* harmony import */ var _routes_5xx_html__WEBPACK_IMPORTED_MODULE_3__ = __webpack_require__(/*! ../../routes/5xx.html */ \"./routes/5xx.html\");\n// This file is generated by Sapper — do not edit it!\n\n\n\n\n\nconst routes = [\n\t{ id: '_', type: 'page', pattern: /^\\/?$/, params: () => ({}), module: _routes_index_html__WEBPACK_IMPORTED_MODULE_0__[\"default\"] },\n\t{ id: 'callback', type: 'page', pattern: /^\\/callback\\/?$/, params: () => ({}), module: _routes_callback_html__WEBPACK_IMPORTED_MODULE_1__[\"default\"] },\n\t{ error: '4xx', module: _routes_4xx_html__WEBPACK_IMPORTED_MODULE_2__[\"default\"] },\n\t{ error: '5xx', module: _routes_5xx_html__WEBPACK_IMPORTED_MODULE_3__[\"default\"] }\n];\n\n//# sourceURL=webpack:///./app/manifest/server.js?");

/***/ }),

/***/ "./app/server.js":
/*!***********************!*\
  !*** ./app/server.js ***!
  \***********************/
/*! no exports provided */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
eval("__webpack_require__.r(__webpack_exports__);\n/* harmony import */ var fs__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! fs */ \"fs\");\n/* harmony import */ var fs__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(fs__WEBPACK_IMPORTED_MODULE_0__);\n/* harmony import */ var express__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! express */ \"express\");\n/* harmony import */ var express__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/__webpack_require__.n(express__WEBPACK_IMPORTED_MODULE_1__);\n/* harmony import */ var compression__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! compression */ \"compression\");\n/* harmony import */ var compression__WEBPACK_IMPORTED_MODULE_2___default = /*#__PURE__*/__webpack_require__.n(compression__WEBPACK_IMPORTED_MODULE_2__);\n/* harmony import */ var sapper__WEBPACK_IMPORTED_MODULE_3__ = __webpack_require__(/*! sapper */ \"sapper\");\n/* harmony import */ var sapper__WEBPACK_IMPORTED_MODULE_3___default = /*#__PURE__*/__webpack_require__.n(sapper__WEBPACK_IMPORTED_MODULE_3__);\n/* harmony import */ var serve_static__WEBPACK_IMPORTED_MODULE_4__ = __webpack_require__(/*! serve-static */ \"serve-static\");\n/* harmony import */ var serve_static__WEBPACK_IMPORTED_MODULE_4___default = /*#__PURE__*/__webpack_require__.n(serve_static__WEBPACK_IMPORTED_MODULE_4__);\n/* harmony import */ var node_fetch__WEBPACK_IMPORTED_MODULE_5__ = __webpack_require__(/*! node-fetch */ \"node-fetch\");\n/* harmony import */ var node_fetch__WEBPACK_IMPORTED_MODULE_5___default = /*#__PURE__*/__webpack_require__.n(node_fetch__WEBPACK_IMPORTED_MODULE_5__);\n/* harmony import */ var _manifest_server_js__WEBPACK_IMPORTED_MODULE_6__ = __webpack_require__(/*! ./manifest/server.js */ \"./app/manifest/server.js\");\n\n\n\n\n\n\n\n\nconst app = express__WEBPACK_IMPORTED_MODULE_1___default()();\n\nconst PORT = 8080;\n\n// this allows us to do e.g. `fetch('/api/blog-posts')` on the server\nglobal.fetch = (url, opts) => {\n\tif (url[0] === '/') url = `https://paperclub.local:${PORT}${url}`;\n\treturn node_fetch__WEBPACK_IMPORTED_MODULE_5___default()(url, opts);\n};\n\napp.use(compression__WEBPACK_IMPORTED_MODULE_2___default()({ threshold: 0 }));\n\napp.use(serve_static__WEBPACK_IMPORTED_MODULE_4___default()('assets'));\n\napp.use(sapper__WEBPACK_IMPORTED_MODULE_3___default()({\n\troutes: _manifest_server_js__WEBPACK_IMPORTED_MODULE_6__[\"routes\"]\n}));\n\napp.listen(PORT, () => {\n\tconsole.log(`listening on port ${PORT}`);\n});\n\n//# sourceURL=webpack:///./app/server.js?");

/***/ }),

/***/ "./routes/4xx.html":
/*!*************************!*\
  !*** ./routes/4xx.html ***!
  \*************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
eval("__webpack_require__.r(__webpack_exports__);\n/* harmony import */ var _components_Layout_html__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./_components/Layout.html */ \"./routes/_components/Layout.html\");\n\n\n\n\nvar _4xx = {};\n\n_4xx.filename = \"/Users/nikolaswise/Department/paper-club/routes/4xx.html\";\n\n_4xx.data = function() {\n\treturn {};\n};\n\n_4xx.render = function(state, options = {}) {\n\tvar components = new Set();\n\n\tfunction addComponent(component) {\n\t\tcomponents.add(component);\n\t}\n\n\tvar result = { head: '', addComponent };\n\tvar html = _4xx._render(result, state, options);\n\n\tvar cssCode = Array.from(components).map(c => c.css && c.css.code).filter(Boolean).join('\\n');\n\n\treturn {\n\t\thtml,\n\t\thead: result.head,\n\t\tcss: { code: cssCode, map: null },\n\t\ttoString() {\n\t\t\treturn html;\n\t\t}\n\t};\n}\n\n_4xx._render = function(__result, state, options) {\n\t__result.addComponent(_4xx);\n\n\tstate = Object.assign({}, state);\n\n\treturn `${(__result.head += `\n\t<title>Not found</title>\n`, \"\")}\n\n${_components_Layout_html__WEBPACK_IMPORTED_MODULE_0__[\"default\"]._render(__result, {page: \"home\"}, { store: options.store, slotted: { default: () => `\n\t<h1 svelte-2131594600>Not found</h1>\n\n\t<p svelte-2131594600>Please check the URL</p>\n` } })}`;\n};\n\n_4xx.css = {\n\tcode: \"h1[svelte-2131594600],p[svelte-2131594600]{text-align:center;margin:0 auto}h1[svelte-2131594600]{font-size:2.8em;text-transform:uppercase;font-weight:700;margin:0 0 0.5em 0}p[svelte-2131594600]{margin:1em auto}@media(min-width: 480px){h1[svelte-2131594600]{font-size:4em}}\",\n\tmap: \"{\\\"version\\\":3,\\\"file\\\":\\\"4xx.html\\\",\\\"sources\\\":[\\\"4xx.html\\\"],\\\"sourcesContent\\\":[\\\"<:Head>\\\\n\\\\t<title>Not found</title>\\\\n</:Head>\\\\n\\\\n<Layout page='home'>\\\\n\\\\t<h1>Not found</h1>\\\\n\\\\n\\\\t<p>Please check the URL</p>\\\\n</Layout>\\\\n\\\\n<style>\\\\n\\\\th1, p {\\\\n\\\\t\\\\ttext-align: center;\\\\n\\\\t\\\\tmargin: 0 auto;\\\\n\\\\t}\\\\n\\\\n\\\\th1 {\\\\n\\\\t\\\\tfont-size: 2.8em;\\\\n\\\\t\\\\ttext-transform: uppercase;\\\\n\\\\t\\\\tfont-weight: 700;\\\\n\\\\t\\\\tmargin: 0 0 0.5em 0;\\\\n\\\\t}\\\\n\\\\n\\\\tp {\\\\n\\\\t\\\\tmargin: 1em auto;\\\\n\\\\t}\\\\n\\\\n\\\\t@media (min-width: 480px) {\\\\n\\\\t\\\\th1 {\\\\n\\\\t\\\\t\\\\tfont-size: 4em;\\\\n\\\\t\\\\t}\\\\n\\\\t}\\\\n</style>\\\\n\\\\n<script>\\\\n\\\\timport Layout from './_components/Layout.html';\\\\n\\\\n\\\\texport default {\\\\n\\\\t\\\\tcomponents: {\\\\n\\\\t\\\\t\\\\tLayout\\\\n\\\\t\\\\t}\\\\n\\\\t};\\\\n</script>\\\\n\\\"],\\\"names\\\":[],\\\"mappings\\\":\\\"AAWC,qBAAE,CAAE,CAAC,mBAAC,CAAC,AACN,UAAU,CAAE,MAAM,CAClB,MAAM,CAAE,CAAC,CAAC,IAAI,AACf,CAAC,AAED,EAAE,mBAAC,CAAC,AACH,SAAS,CAAE,KAAK,CAChB,cAAc,CAAE,SAAS,CACzB,WAAW,CAAE,GAAG,CAChB,MAAM,CAAE,CAAC,CAAC,CAAC,CAAC,KAAK,CAAC,CAAC,AACpB,CAAC,AAED,CAAC,mBAAC,CAAC,AACF,MAAM,CAAE,GAAG,CAAC,IAAI,AACjB,CAAC,AAED,MAAM,AAAC,YAAY,KAAK,CAAC,AAAC,CAAC,AAC1B,EAAE,mBAAC,CAAC,AACH,SAAS,CAAE,GAAG,AACf,CAAC,AACF,CAAC\\\"}\"\n};\n\nvar warned = false;\n_4xx.renderCss = function() {\n\tif (!warned) {\n\t\tconsole.error('Component.renderCss(...) is deprecated and will be removed in v2 — use Component.render(...).css instead');\n\t\twarned = true;\n\t}\n\n\tvar components = [];\n\n\tcomponents.push({\n\t\tfilename: _4xx.filename,\n\t\tcss: _4xx.css && _4xx.css.code,\n\t\tmap: _4xx.css && _4xx.css.map\n\t});\n\n\tvar seen = {};\n\n\tfunction addComponent(component) {\n\t\tvar result = component.renderCss();\n\t\tresult.components.forEach(x => {\n\t\t\tif (seen[x.filename]) return;\n\t\t\tseen[x.filename] = true;\n\t\t\tcomponents.push(x);\n\t\t});\n\t}\n\n\taddComponent(_components_Layout_html__WEBPACK_IMPORTED_MODULE_0__[\"default\"]);\n\n\treturn {\n\t\tcss: components.map(x => x.css).join('\\n'),\n\t\tmap: null,\n\t\tcomponents\n\t};\n};\n/* harmony default export */ __webpack_exports__[\"default\"] = (_4xx);\n\n//# sourceURL=webpack:///./routes/4xx.html?");

/***/ }),

/***/ "./routes/5xx.html":
/*!*************************!*\
  !*** ./routes/5xx.html ***!
  \*************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
eval("__webpack_require__.r(__webpack_exports__);\n/* harmony import */ var _components_Layout_html__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./_components/Layout.html */ \"./routes/_components/Layout.html\");\n\n\n\n\nvar _5xx = {};\n\n_5xx.filename = \"/Users/nikolaswise/Department/paper-club/routes/5xx.html\";\n\n_5xx.data = function() {\n\treturn {};\n};\n\n_5xx.render = function(state, options = {}) {\n\tvar components = new Set();\n\n\tfunction addComponent(component) {\n\t\tcomponents.add(component);\n\t}\n\n\tvar result = { head: '', addComponent };\n\tvar html = _5xx._render(result, state, options);\n\n\tvar cssCode = Array.from(components).map(c => c.css && c.css.code).filter(Boolean).join('\\n');\n\n\treturn {\n\t\thtml,\n\t\thead: result.head,\n\t\tcss: { code: cssCode, map: null },\n\t\ttoString() {\n\t\t\treturn html;\n\t\t}\n\t};\n}\n\n_5xx._render = function(__result, state, options) {\n\t__result.addComponent(_5xx);\n\n\tstate = Object.assign({}, state);\n\n\treturn `${(__result.head += `\n\t<title>Internal server error</title>\n`, \"\")}\n\n${_components_Layout_html__WEBPACK_IMPORTED_MODULE_0__[\"default\"]._render(__result, {page: \"home\"}, { store: options.store, slotted: { default: () => `\n\t<h1 svelte-2402814044>Internal server error</h1>\n` } })}`;\n};\n\n_5xx.css = {\n\tcode: \"h1[svelte-2402814044]{text-align:center;margin:0 auto;font-size:2.8em;text-transform:uppercase;font-weight:700;margin:0 0 0.5em 0}@media(min-width: 480px){h1[svelte-2402814044]{font-size:4em}}\",\n\tmap: \"{\\\"version\\\":3,\\\"file\\\":\\\"5xx.html\\\",\\\"sources\\\":[\\\"5xx.html\\\"],\\\"sourcesContent\\\":[\\\"<:Head>\\\\n\\\\t<title>Internal server error</title>\\\\n</:Head>\\\\n\\\\n<Layout page='home'>\\\\n\\\\t<h1>Internal server error</h1>\\\\n</Layout>\\\\n\\\\n<style>\\\\n\\\\th1 {\\\\n\\\\t\\\\ttext-align: center;\\\\n\\\\t\\\\tmargin: 0 auto;\\\\n\\\\t\\\\tfont-size: 2.8em;\\\\n\\\\t\\\\ttext-transform: uppercase;\\\\n\\\\t\\\\tfont-weight: 700;\\\\n\\\\t\\\\tmargin: 0 0 0.5em 0;\\\\n\\\\t}\\\\n\\\\n\\\\t@media (min-width: 480px) {\\\\n\\\\t\\\\th1 {\\\\n\\\\t\\\\t\\\\tfont-size: 4em;\\\\n\\\\t\\\\t}\\\\n\\\\t}\\\\n</style>\\\\n\\\\n<script>\\\\n\\\\timport Layout from './_components/Layout.html';\\\\n\\\\n\\\\texport default {\\\\n\\\\t\\\\tcomponents: {\\\\n\\\\t\\\\t\\\\tLayout\\\\n\\\\t\\\\t}\\\\n\\\\t};\\\\n</script>\\\\n\\\"],\\\"names\\\":[],\\\"mappings\\\":\\\"AASC,EAAE,mBAAC,CAAC,AACH,UAAU,CAAE,MAAM,CAClB,MAAM,CAAE,CAAC,CAAC,IAAI,CACd,SAAS,CAAE,KAAK,CAChB,cAAc,CAAE,SAAS,CACzB,WAAW,CAAE,GAAG,CAChB,MAAM,CAAE,CAAC,CAAC,CAAC,CAAC,KAAK,CAAC,CAAC,AACpB,CAAC,AAED,MAAM,AAAC,YAAY,KAAK,CAAC,AAAC,CAAC,AAC1B,EAAE,mBAAC,CAAC,AACH,SAAS,CAAE,GAAG,AACf,CAAC,AACF,CAAC\\\"}\"\n};\n\nvar warned = false;\n_5xx.renderCss = function() {\n\tif (!warned) {\n\t\tconsole.error('Component.renderCss(...) is deprecated and will be removed in v2 — use Component.render(...).css instead');\n\t\twarned = true;\n\t}\n\n\tvar components = [];\n\n\tcomponents.push({\n\t\tfilename: _5xx.filename,\n\t\tcss: _5xx.css && _5xx.css.code,\n\t\tmap: _5xx.css && _5xx.css.map\n\t});\n\n\tvar seen = {};\n\n\tfunction addComponent(component) {\n\t\tvar result = component.renderCss();\n\t\tresult.components.forEach(x => {\n\t\t\tif (seen[x.filename]) return;\n\t\t\tseen[x.filename] = true;\n\t\t\tcomponents.push(x);\n\t\t});\n\t}\n\n\taddComponent(_components_Layout_html__WEBPACK_IMPORTED_MODULE_0__[\"default\"]);\n\n\treturn {\n\t\tcss: components.map(x => x.css).join('\\n'),\n\t\tmap: null,\n\t\tcomponents\n\t};\n};\n/* harmony default export */ __webpack_exports__[\"default\"] = (_5xx);\n\n//# sourceURL=webpack:///./routes/5xx.html?");

/***/ }),

/***/ "./routes/_components/Layout.html":
/*!****************************************!*\
  !*** ./routes/_components/Layout.html ***!
  \****************************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
eval("__webpack_require__.r(__webpack_exports__);\n/* harmony import */ var _Nav_html__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./Nav.html */ \"./routes/_components/Nav.html\");\n\n\n\n\nvar Layout = {};\n\nLayout.filename = \"/Users/nikolaswise/Department/paper-club/routes/_components/Layout.html\";\n\nLayout.data = function() {\n\treturn {};\n};\n\nLayout.render = function(state, options = {}) {\n\tvar components = new Set();\n\n\tfunction addComponent(component) {\n\t\tcomponents.add(component);\n\t}\n\n\tvar result = { head: '', addComponent };\n\tvar html = Layout._render(result, state, options);\n\n\tvar cssCode = Array.from(components).map(c => c.css && c.css.code).filter(Boolean).join('\\n');\n\n\treturn {\n\t\thtml,\n\t\thead: result.head,\n\t\tcss: { code: cssCode, map: null },\n\t\ttoString() {\n\t\t\treturn html;\n\t\t}\n\t};\n}\n\nLayout._render = function(__result, state, options) {\n\t__result.addComponent(Layout);\n\n\tstate = Object.assign({}, state);\n\n\treturn `${_Nav_html__WEBPACK_IMPORTED_MODULE_0__[\"default\"]._render(__result, {page: state.page}, { store: options.store })}\n\n<main>\n\t${options && options.slotted && options.slotted.default ? options.slotted.default() : ``}\n</main>`;\n};\n\nLayout.css = {\n\tcode: '',\n\tmap: null\n};\n\nvar warned = false;\nLayout.renderCss = function() {\n\tif (!warned) {\n\t\tconsole.error('Component.renderCss(...) is deprecated and will be removed in v2 — use Component.render(...).css instead');\n\t\twarned = true;\n\t}\n\n\tvar components = [];\n\n\tvar seen = {};\n\n\tfunction addComponent(component) {\n\t\tvar result = component.renderCss();\n\t\tresult.components.forEach(x => {\n\t\t\tif (seen[x.filename]) return;\n\t\t\tseen[x.filename] = true;\n\t\t\tcomponents.push(x);\n\t\t});\n\t}\n\n\taddComponent(_Nav_html__WEBPACK_IMPORTED_MODULE_0__[\"default\"]);\n\n\treturn {\n\t\tcss: components.map(x => x.css).join('\\n'),\n\t\tmap: null,\n\t\tcomponents\n\t};\n};\n/* harmony default export */ __webpack_exports__[\"default\"] = (Layout);\n\n//# sourceURL=webpack:///./routes/_components/Layout.html?");

/***/ }),

/***/ "./routes/_components/Login.html":
/*!***************************************!*\
  !*** ./routes/_components/Login.html ***!
  \***************************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
eval("__webpack_require__.r(__webpack_exports__);\nfunction data() {\n  return {\n    state: 'hide'\n  }\n};\n\nvar Login = {};\n\nLogin.filename = \"/Users/nikolaswise/Department/paper-club/routes/_components/Login.html\";\n\nLogin.data = function() {\n\treturn data();\n};\n\nLogin.render = function(state, options = {}) {\n\tvar components = new Set();\n\n\tfunction addComponent(component) {\n\t\tcomponents.add(component);\n\t}\n\n\tvar result = { head: '', addComponent };\n\tvar html = Login._render(result, state, options);\n\n\tvar cssCode = Array.from(components).map(c => c.css && c.css.code).filter(Boolean).join('\\n');\n\n\treturn {\n\t\thtml,\n\t\thead: result.head,\n\t\tcss: { code: cssCode, map: null },\n\t\ttoString() {\n\t\t\treturn html;\n\t\t}\n\t};\n}\n\nLogin._render = function(__result, state, options) {\n\t__result.addComponent(Login);\n\n\tstate = Object.assign(data(), state);\n\n\treturn `${ state.user ? `<p>${__escape(state.user.nickname)}</p>\n  <button>login</button>` : `<button>login</button>` }\n\n<div class=\"${__escape(state.state)}\">\n  <p>Magic Link Sign In:</p>\n  <input class=\"js-email\" type=\"email\" placeholder=\"email\">\n  <button>Send Email</button>\n</div>`;\n};\n\nLogin.css = {\n\tcode: '',\n\tmap: null\n};\n\nvar warned = false;\nLogin.renderCss = function() {\n\tif (!warned) {\n\t\tconsole.error('Component.renderCss(...) is deprecated and will be removed in v2 — use Component.render(...).css instead');\n\t\twarned = true;\n\t}\n\n\tvar components = [];\n\n\treturn {\n\t\tcss: components.map(x => x.css).join('\\n'),\n\t\tmap: null,\n\t\tcomponents\n\t};\n};\n\nvar escaped = {\n\t'\"': '&quot;',\n\t\"'\": '&#39;',\n\t'&': '&amp;',\n\t'<': '&lt;',\n\t'>': '&gt;'\n};\n\nfunction __escape(html) {\n\treturn String(html).replace(/[\"'&<>]/g, match => escaped[match]);\n}\n/* harmony default export */ __webpack_exports__[\"default\"] = (Login);\n\n//# sourceURL=webpack:///./routes/_components/Login.html?");

/***/ }),

/***/ "./routes/_components/Nav.html":
/*!*************************************!*\
  !*** ./routes/_components/Nav.html ***!
  \*************************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
eval("__webpack_require__.r(__webpack_exports__);\n/* harmony import */ var _Login_html__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./Login.html */ \"./routes/_components/Login.html\");\n\n\n\n\nvar Nav = {};\n\nNav.filename = \"/Users/nikolaswise/Department/paper-club/routes/_components/Nav.html\";\n\nNav.data = function() {\n\treturn {};\n};\n\nNav.render = function(state, options = {}) {\n\tvar components = new Set();\n\n\tfunction addComponent(component) {\n\t\tcomponents.add(component);\n\t}\n\n\tvar result = { head: '', addComponent };\n\tvar html = Nav._render(result, state, options);\n\n\tvar cssCode = Array.from(components).map(c => c.css && c.css.code).filter(Boolean).join('\\n');\n\n\treturn {\n\t\thtml,\n\t\thead: result.head,\n\t\tcss: { code: cssCode, map: null },\n\t\ttoString() {\n\t\t\treturn html;\n\t\t}\n\t};\n}\n\nNav._render = function(__result, state, options) {\n\t__result.addComponent(Nav);\n\n\tstate = Object.assign({}, state);\n\n\treturn `<nav>\n  ${_Login_html__WEBPACK_IMPORTED_MODULE_0__[\"default\"]._render(__result, {}, { store: options.store })}\n</nav>`;\n};\n\nNav.css = {\n\tcode: '',\n\tmap: null\n};\n\nvar warned = false;\nNav.renderCss = function() {\n\tif (!warned) {\n\t\tconsole.error('Component.renderCss(...) is deprecated and will be removed in v2 — use Component.render(...).css instead');\n\t\twarned = true;\n\t}\n\n\tvar components = [];\n\n\tvar seen = {};\n\n\tfunction addComponent(component) {\n\t\tvar result = component.renderCss();\n\t\tresult.components.forEach(x => {\n\t\t\tif (seen[x.filename]) return;\n\t\t\tseen[x.filename] = true;\n\t\t\tcomponents.push(x);\n\t\t});\n\t}\n\n\taddComponent(_Login_html__WEBPACK_IMPORTED_MODULE_0__[\"default\"]);\n\n\treturn {\n\t\tcss: components.map(x => x.css).join('\\n'),\n\t\tmap: null,\n\t\tcomponents\n\t};\n};\n/* harmony default export */ __webpack_exports__[\"default\"] = (Nav);\n\n//# sourceURL=webpack:///./routes/_components/Nav.html?");

/***/ }),

/***/ "./routes/callback.html":
/*!******************************!*\
  !*** ./routes/callback.html ***!
  \******************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
eval("__webpack_require__.r(__webpack_exports__);\n/* harmony import */ var _components_Layout_html__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./_components/Layout.html */ \"./routes/_components/Layout.html\");\n\n\nfunction preload({ params, query }) {};\n\nvar Callback = {};\n\nCallback.filename = \"/Users/nikolaswise/Department/paper-club/routes/callback.html\";\n\nCallback.data = function() {\n\treturn {};\n};\n\nCallback.render = function(state, options = {}) {\n\tvar components = new Set();\n\n\tfunction addComponent(component) {\n\t\tcomponents.add(component);\n\t}\n\n\tvar result = { head: '', addComponent };\n\tvar html = Callback._render(result, state, options);\n\n\tvar cssCode = Array.from(components).map(c => c.css && c.css.code).filter(Boolean).join('\\n');\n\n\treturn {\n\t\thtml,\n\t\thead: result.head,\n\t\tcss: { code: cssCode, map: null },\n\t\ttoString() {\n\t\t\treturn html;\n\t\t}\n\t};\n}\n\nCallback._render = function(__result, state, options) {\n\t__result.addComponent(Callback);\n\n\tstate = Object.assign({}, state);\n\n\treturn `${(__result.head += `\n\t<title>Sapper project template</title>\n`, \"\")}\n\n${_components_Layout_html__WEBPACK_IMPORTED_MODULE_0__[\"default\"]._render(__result, {page: \"callback\"}, { store: options.store, slotted: { default: () => `\n\t<h1>You did it!</h1>\n` } })}`;\n};\n\nCallback.css = {\n\tcode: '',\n\tmap: null\n};\n\nvar warned = false;\nCallback.renderCss = function() {\n\tif (!warned) {\n\t\tconsole.error('Component.renderCss(...) is deprecated and will be removed in v2 — use Component.render(...).css instead');\n\t\twarned = true;\n\t}\n\n\tvar components = [];\n\n\tvar seen = {};\n\n\tfunction addComponent(component) {\n\t\tvar result = component.renderCss();\n\t\tresult.components.forEach(x => {\n\t\t\tif (seen[x.filename]) return;\n\t\t\tseen[x.filename] = true;\n\t\t\tcomponents.push(x);\n\t\t});\n\t}\n\n\taddComponent(_components_Layout_html__WEBPACK_IMPORTED_MODULE_0__[\"default\"]);\n\n\treturn {\n\t\tcss: components.map(x => x.css).join('\\n'),\n\t\tmap: null,\n\t\tcomponents\n\t};\n};\n\nCallback.preload = preload;\n/* harmony default export */ __webpack_exports__[\"default\"] = (Callback);\n\n//# sourceURL=webpack:///./routes/callback.html?");

/***/ }),

/***/ "./routes/index.html":
/*!***************************!*\
  !*** ./routes/index.html ***!
  \***************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
eval("__webpack_require__.r(__webpack_exports__);\n/* harmony import */ var _components_Layout_html__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./_components/Layout.html */ \"./routes/_components/Layout.html\");\n\n\nfunction preload({ params, query }) {};\n\nvar Index = {};\n\nIndex.filename = \"/Users/nikolaswise/Department/paper-club/routes/index.html\";\n\nIndex.data = function() {\n\treturn {};\n};\n\nIndex.render = function(state, options = {}) {\n\tvar components = new Set();\n\n\tfunction addComponent(component) {\n\t\tcomponents.add(component);\n\t}\n\n\tvar result = { head: '', addComponent };\n\tvar html = Index._render(result, state, options);\n\n\tvar cssCode = Array.from(components).map(c => c.css && c.css.code).filter(Boolean).join('\\n');\n\n\treturn {\n\t\thtml,\n\t\thead: result.head,\n\t\tcss: { code: cssCode, map: null },\n\t\ttoString() {\n\t\t\treturn html;\n\t\t}\n\t};\n}\n\nIndex._render = function(__result, state, options) {\n\t__result.addComponent(Index);\n\n\tstate = Object.assign({}, state);\n\n\treturn `${(__result.head += `\n\t<title>Sapper project template</title>\n`, \"\")}\n\n${_components_Layout_html__WEBPACK_IMPORTED_MODULE_0__[\"default\"]._render(__result, {page: \"home\"}, { store: options.store, slotted: { default: () => `\n\t<h1>Paper Club</h1>\n` } })}`;\n};\n\nIndex.css = {\n\tcode: '',\n\tmap: null\n};\n\nvar warned = false;\nIndex.renderCss = function() {\n\tif (!warned) {\n\t\tconsole.error('Component.renderCss(...) is deprecated and will be removed in v2 — use Component.render(...).css instead');\n\t\twarned = true;\n\t}\n\n\tvar components = [];\n\n\tvar seen = {};\n\n\tfunction addComponent(component) {\n\t\tvar result = component.renderCss();\n\t\tresult.components.forEach(x => {\n\t\t\tif (seen[x.filename]) return;\n\t\t\tseen[x.filename] = true;\n\t\t\tcomponents.push(x);\n\t\t});\n\t}\n\n\taddComponent(_components_Layout_html__WEBPACK_IMPORTED_MODULE_0__[\"default\"]);\n\n\treturn {\n\t\tcss: components.map(x => x.css).join('\\n'),\n\t\tmap: null,\n\t\tcomponents\n\t};\n};\n\nIndex.preload = preload;\n/* harmony default export */ __webpack_exports__[\"default\"] = (Index);\n\n//# sourceURL=webpack:///./routes/index.html?");

/***/ }),

/***/ "compression":
/*!******************************!*\
  !*** external "compression" ***!
  \******************************/
/*! no static exports found */
/***/ (function(module, exports) {

eval("module.exports = require(\"compression\");\n\n//# sourceURL=webpack:///external_%22compression%22?");

/***/ }),

/***/ "express":
/*!**************************!*\
  !*** external "express" ***!
  \**************************/
/*! no static exports found */
/***/ (function(module, exports) {

eval("module.exports = require(\"express\");\n\n//# sourceURL=webpack:///external_%22express%22?");

/***/ }),

/***/ "fs":
/*!*********************!*\
  !*** external "fs" ***!
  \*********************/
/*! no static exports found */
/***/ (function(module, exports) {

eval("module.exports = require(\"fs\");\n\n//# sourceURL=webpack:///external_%22fs%22?");

/***/ }),

/***/ "node-fetch":
/*!*****************************!*\
  !*** external "node-fetch" ***!
  \*****************************/
/*! no static exports found */
/***/ (function(module, exports) {

eval("module.exports = require(\"node-fetch\");\n\n//# sourceURL=webpack:///external_%22node-fetch%22?");

/***/ }),

/***/ "sapper":
/*!*************************!*\
  !*** external "sapper" ***!
  \*************************/
/*! no static exports found */
/***/ (function(module, exports) {

eval("module.exports = require(\"sapper\");\n\n//# sourceURL=webpack:///external_%22sapper%22?");

/***/ }),

/***/ "serve-static":
/*!*******************************!*\
  !*** external "serve-static" ***!
  \*******************************/
/*! no static exports found */
/***/ (function(module, exports) {

eval("module.exports = require(\"serve-static\");\n\n//# sourceURL=webpack:///external_%22serve-static%22?");

/***/ })

/******/ });