// This file is generated by Sapper — do not edit it!
export const routes = [
	{ pattern: /^\/?$/, params: () => ({}), load: () => import(/* webpackChunkName: "_" */ '../../routes/index.html') },
	{ pattern: /^\/login\/?$/, params: () => ({}), load: () => import(/* webpackChunkName: "login" */ '../../routes/login.html') },
	{ error: '4xx', load: () => import(/* webpackChunkName: "_4xx" */ '../../routes/4xx.html') },
	{ error: '5xx', load: () => import(/* webpackChunkName: "_5xx" */ '../../routes/5xx.html') }
];

if (module.hot) {
	import('/Users/nikolaswise/Department/paper-club/node_modules/sapper/sapper-dev-client.js').then(client => {
		client.connect(10000);
	});
}