// This file is generated by Sapper — do not edit it!
export const routes = [
	{ pattern: /^\/?$/, params: () => ({}), load: () => import(/* webpackChunkName: "_" */ '../../routes/index.html') },
	{ pattern: /^\/publisher\/id\/?$/, params: () => ({}), load: () => import(/* webpackChunkName: "publisher_id" */ '../../routes/publisher/id.html') },
	{ pattern: /^\/callback\/?$/, params: () => ({}), load: () => import(/* webpackChunkName: "callback" */ '../../routes/callback.html') },
	{ pattern: /^\/account\/?$/, params: () => ({}), load: () => import(/* webpackChunkName: "account" */ '../../routes/account/index.html') },
	{ pattern: /^\/account\/settings\/?$/, params: () => ({}), load: () => import(/* webpackChunkName: "account_settings" */ '../../routes/account/settings/index.html') },
	{ pattern: /^\/account\/settings\/edit-card\/?$/, params: () => ({}), load: () => import(/* webpackChunkName: "account_settings_edit_card" */ '../../routes/account/settings/edit-card.html') },
	{ pattern: /^\/account\/settings\/add-card\/?$/, params: () => ({}), load: () => import(/* webpackChunkName: "account_settings_add_card" */ '../../routes/account/settings/add-card.html') },
	{ pattern: /^\/account\/orders\/id\/?$/, params: () => ({}), load: () => import(/* webpackChunkName: "account_orders_id" */ '../../routes/account/orders/id.html') },
	{ pattern: /^\/account\/items\/?$/, params: () => ({}), load: () => import(/* webpackChunkName: "account_items" */ '../../routes/account/items/index.html') },
	{ pattern: /^\/account\/items\/edit\/?$/, params: () => ({}), load: () => import(/* webpackChunkName: "account_items_edit" */ '../../routes/account/items/edit.html') },
	{ pattern: /^\/account\/items\/new\/?$/, params: () => ({}), load: () => import(/* webpackChunkName: "account_items_new" */ '../../routes/account/items/new.html') },
	{ pattern: /^\/artist\/id\/?$/, params: () => ({}), load: () => import(/* webpackChunkName: "artist_id" */ '../../routes/artist/id.html') },
	{ pattern: /^\/user\/id\/?$/, params: () => ({}), load: () => import(/* webpackChunkName: "user_id" */ '../../routes/user/id.html') },
	{ pattern: /^\/item\/id\/?$/, params: () => ({}), load: () => import(/* webpackChunkName: "item_id" */ '../../routes/item/id.html') },
	{ error: '5xx', load: () => import(/* webpackChunkName: "_5xx" */ '../../routes/5xx.html') },
	{ error: '4xx', load: () => import(/* webpackChunkName: "_4xx" */ '../../routes/4xx.html') }
];

if (module.hot) {
	import('/Users/nikolaswise/Department/paper-club/node_modules/sapper/sapper-dev-client.js').then(client => {
		client.connect(10000);
	});
}