// This file is generated by Sapper — do not edit it!
export const routes = [
	{ pattern: /^\/?$/, params: () => ({}), load: () => import(/* webpackChunkName: "_" */ '../../routes/index.html') },
	{ pattern: /^\/book-club\/?$/, params: () => ({}), load: () => import(/* webpackChunkName: "book_club" */ '../../routes/book-club/index.html') },
	{ pattern: /^\/portfolio\/?$/, params: () => ({}), load: () => import(/* webpackChunkName: "portfolio" */ '../../routes/portfolio.html') },
	{ pattern: /^\/contact\/?$/, params: () => ({}), load: () => import(/* webpackChunkName: "contact" */ '../../routes/contact.html') },
	{ pattern: /^\/about\/?$/, params: () => ({}), load: () => import(/* webpackChunkName: "about" */ '../../routes/about.html') },
	{ pattern: /^\/news\/?$/, params: () => ({}), load: () => import(/* webpackChunkName: "news" */ '../../routes/news/index.html') },
	{ error: '4xx', load: () => import(/* webpackChunkName: "_4xx" */ '../../routes/4xx.html') },
	{ error: '5xx', load: () => import(/* webpackChunkName: "_5xx" */ '../../routes/5xx.html') }
];