// This file is generated by Sapper — do not edit it!
export const timestamp = 1525839394752;

export const assets = [
	"favicon.png",
	"global.css",
	"great-success.png",
	"manifest.json",
	"svelte-logo-192.png",
	"svelte-logo-512.png"
];

export const shell = [
	"/client/3ff939b3ba2f839b0163/account_orders_id.account_orders_id.js",
	"/client/3ff939b3ba2f839b0163/_._.js",
	"/client/3ff939b3ba2f839b0163/_5xx._5xx.js",
	"/client/3ff939b3ba2f839b0163/_~_4xx~_5xx~account~account_items~account_items_edit~account_items_new~account_orders_id~account_set~afba5f34._~_4xx~_5xx~account~account_items~account_items_edit~account_items_new~account_orders_id~account_set~afba5f34.js",
	"/client/3ff939b3ba2f839b0163/account.account.js",
	"/client/3ff939b3ba2f839b0163/account_items.account_items.js",
	"/client/3ff939b3ba2f839b0163/0.0.js",
	"/client/3ff939b3ba2f839b0163/account_items_edit.account_items_edit.js",
	"/client/3ff939b3ba2f839b0163/account_items_new.account_items_new.js",
	"/client/3ff939b3ba2f839b0163/_4xx._4xx.js",
	"/client/3ff939b3ba2f839b0163/account_settings.account_settings.js",
	"/client/3ff939b3ba2f839b0163/account_settings_add_card.account_settings_add_card.js",
	"/client/3ff939b3ba2f839b0163/account_settings_edit_card.account_settings_edit_card.js",
	"/client/3ff939b3ba2f839b0163/artist_id.artist_id.js",
	"/client/3ff939b3ba2f839b0163/callback.callback.js",
	"/client/3ff939b3ba2f839b0163/item_id.item_id.js",
	"/client/3ff939b3ba2f839b0163/main.js",
	"/client/3ff939b3ba2f839b0163/publisher_id.publisher_id.js",
	"/client/3ff939b3ba2f839b0163/user_id.user_id.js"
];

export const routes = [
	{ pattern: /^\/?$/ },
	{ pattern: /^\/publisher\/id\/?$/ },
	{ pattern: /^\/callback\/?$/ },
	{ pattern: /^\/account\/?$/ },
	{ pattern: /^\/account\/settings\/?$/ },
	{ pattern: /^\/account\/settings\/edit-card\/?$/ },
	{ pattern: /^\/account\/settings\/add-card\/?$/ },
	{ pattern: /^\/account\/orders\/id\/?$/ },
	{ pattern: /^\/account\/items\/?$/ },
	{ pattern: /^\/account\/items\/edit\/?$/ },
	{ pattern: /^\/account\/items\/new\/?$/ },
	{ pattern: /^\/artist\/id\/?$/ },
	{ pattern: /^\/user\/id\/?$/ },
	{ pattern: /^\/item\/id\/?$/ }
];