// This file is generated by Sapper — do not edit it!
export const timestamp = 1525041819908;

export const assets = [
	"favicon.png",
	"global.css",
	"great-success.png",
	"manifest.json",
	"svelte-logo-192.png",
	"svelte-logo-512.png"
];

export const shell = [
	"/client/69c10e5c2130c2d651cd/_._.js",
	"/client/69c10e5c2130c2d651cd/_4xx._4xx.js",
	"/client/69c10e5c2130c2d651cd/_5xx._5xx.js",
	"/client/69c10e5c2130c2d651cd/callback.callback.js",
	"/client/69c10e5c2130c2d651cd/main.js",
	"/client/69c10e5c2130c2d651cd/0.0.js",
	"/client/69c10e5c2130c2d651cd/_~_4xx~_5xx~callback._~_4xx~_5xx~callback.js",
	"/client/_~_4xx~_5xx~callback.2291853ff5aa31c03cae.hot-update.js",
	"/client/2291853ff5aa31c03cae.hot-update.json"
];

export const routes = [
	{ pattern: /^\/?$/ },
	{ pattern: /^\/callback\/?$/ }
];