// This file is generated by Sapper — do not edit it!
export const timestamp = 1525032994774;

export const assets = [
	"favicon.png",
	"global.css",
	"great-success.png",
	"manifest.json",
	"svelte-logo-192.png",
	"svelte-logo-512.png"
];

export const shell = [
	"/client/e9febc82d1ba2fa78a34/_._.js",
	"/client/e9febc82d1ba2fa78a34/_4xx._4xx.js",
	"/client/e9febc82d1ba2fa78a34/_5xx._5xx.js",
	"/client/e9febc82d1ba2fa78a34/login.login.js",
	"/client/e9febc82d1ba2fa78a34/main.js",
	"/client/e9febc82d1ba2fa78a34/0.0.js"
];

export const routes = [
	{ pattern: /^\/?$/ },
	{ pattern: /^\/login\/?$/ }
];