// This file is generated by Sapper — do not edit it!
import _ from '../../routes/index.html';
import publisher_id from '../../routes/publisher/id.html';
import callback from '../../routes/callback.html';
import account from '../../routes/account/index.html';
import account_settings from '../../routes/account/settings/index.html';
import account_settings_edit_card from '../../routes/account/settings/edit-card.html';
import account_settings_add_card from '../../routes/account/settings/add-card.html';
import account_orders_id from '../../routes/account/orders/id.html';
import account_items from '../../routes/account/items/index.html';
import account_items_edit from '../../routes/account/items/edit.html';
import account_items_new from '../../routes/account/items/new.html';
import artist_id from '../../routes/artist/id.html';
import user_id from '../../routes/user/id.html';
import item_id from '../../routes/item/id.html';
import _5xx from '../../routes/5xx.html';
import _4xx from '../../routes/4xx.html';

export const routes = [
	{ id: '_', type: 'page', pattern: /^\/?$/, params: () => ({}), module: _ },
	{ id: 'publisher_id', type: 'page', pattern: /^\/publisher\/id\/?$/, params: () => ({}), module: publisher_id },
	{ id: 'callback', type: 'page', pattern: /^\/callback\/?$/, params: () => ({}), module: callback },
	{ id: 'account', type: 'page', pattern: /^\/account\/?$/, params: () => ({}), module: account },
	{ id: 'account_settings', type: 'page', pattern: /^\/account\/settings\/?$/, params: () => ({}), module: account_settings },
	{ id: 'account_settings_edit_card', type: 'page', pattern: /^\/account\/settings\/edit-card\/?$/, params: () => ({}), module: account_settings_edit_card },
	{ id: 'account_settings_add_card', type: 'page', pattern: /^\/account\/settings\/add-card\/?$/, params: () => ({}), module: account_settings_add_card },
	{ id: 'account_orders_id', type: 'page', pattern: /^\/account\/orders\/id\/?$/, params: () => ({}), module: account_orders_id },
	{ id: 'account_items', type: 'page', pattern: /^\/account\/items\/?$/, params: () => ({}), module: account_items },
	{ id: 'account_items_edit', type: 'page', pattern: /^\/account\/items\/edit\/?$/, params: () => ({}), module: account_items_edit },
	{ id: 'account_items_new', type: 'page', pattern: /^\/account\/items\/new\/?$/, params: () => ({}), module: account_items_new },
	{ id: 'artist_id', type: 'page', pattern: /^\/artist\/id\/?$/, params: () => ({}), module: artist_id },
	{ id: 'user_id', type: 'page', pattern: /^\/user\/id\/?$/, params: () => ({}), module: user_id },
	{ id: 'item_id', type: 'page', pattern: /^\/item\/id\/?$/, params: () => ({}), module: item_id },
	{ error: '5xx', module: _5xx },
	{ error: '4xx', module: _4xx }
];