// This file is generated by Sapper — do not edit it!
import _ from '../../routes/index.html';
import login from '../../routes/login.html';
import _4xx from '../../routes/4xx.html';
import _5xx from '../../routes/5xx.html';

export const routes = [
	{ id: '_', type: 'page', pattern: /^\/?$/, params: () => ({}), module: _ },
	{ id: 'login', type: 'page', pattern: /^\/login\/?$/, params: () => ({}), module: login },
	{ error: '4xx', module: _4xx },
	{ error: '5xx', module: _5xx }
];